# Generated by Django 6.0.1 on 2026-02-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_order_customer_address_order_customer_phone_and_more'),
        ('pages', '0002_order_fulfilled_by'),
    ]

    operations = [
    ]
